import type { Metadata } from "next";
import "@/app/globals.css";
import "./globals.css";
import Navbar from "./components/organisms/Navbar";

console.log('How ooooo')
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="px-60 bg-red-200 mt-16">{children}</div>
      </body>
    </html>
  );
}