name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main # Adjust this to your default branch name (e.g., "main" or "master")
  pull_request:
    branches:
      - main # Optional: Trigger on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust based on your project requirements

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy job only runs after the build job completes successfully
    environment: production

    steps:
      # Checkout code (again to ensure it's available for deployment)
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js (again for consistency)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-branch: ${{ github.ref }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
